FROM golang:1.24-alpine AS builder

ENV SERVER_PORT=5000
ENV MONGO_URI=mongodb://admin:admin@mongodb:27017/

WORKDIR /app

COPY . .

RUN go mod download

RUN go install github.com/air-verse/air@latest

CMD ["air","-c",".air.toml"]